#%RAML 1.0

title: Account APIs
version: v1
baseUri: https://ebpi-api.yoganand.com/account


### Plugin configuration ###
uses:
  ramltojaxrs: ramltojaxrs.raml
  ramltopojo: ramltopojo.raml
  common-types: types/common.raml

